### PR TITLE
Fix realms loading issue due to createClient plugin init order

### LINKED ISSUE #1302: pickRealm silently fails to connect
```
'use strict'

const mineflayer = require('mineflayer')

const [,, username, realmName] = process.argv
if (!realmName) {
  console.log('Usage : node client_realms.js <username/email> <realm_name>')
  process.exit(1)
}

const client = mineflayer.createBot({
  realms: {
    pickRealm: (realms) => realms.find(e => e.name === realmName) // Connect the client to a Realm using a function that returns a Realm
  },
  username,
  auth: 'microsoft' // This option must be present and set to 'microsoft' to  join a Realm.
})

client.on('connect', function () {
  console.info('connected')
})

client.on('disconnect', function (packet) {
  console.log('disconnected: ' + packet.reason)
})
```

prints  connected, but never actually connects to realm.

### PR DESCRIPTION
**Pull request by extremeheat**
* Fix loading plugins before realm host/port have been obtained
  * Fix #1302 
* Fix https://github.com/PrismarineJS/node-minecraft-protocol/issues/1281 types

### CODE REVIEW

File: src/client/versionChecking.js [hunk 1]
```diff
@@ -10,7 +10,6 @@ module.exports = function (client, options) {
     try {
       parsed = JSON.parse(message.reason)
     } catch (error) {
-      client.emit('error', error)
```
Comment (rom1504) [inline src/client/versionChecking.js:13]: Why do we want to ignore this error?

Comment (extremeheat) [reply src/client/versionChecking.js:13]: Related to https://github.com/PrismarineJS/node-minecraft-protocol/issues/1290 

The code below checks if the kick message contains an outdated version message, but it's essential. And since the `reason` field is actually a JSON chat message it's still valid for the server to send a plain string (ie "hello world" as opposed to {"text":"hello world"}) as opposed to JSON, as the chat parsing code will accept it. So to correctly parse it we would have to import prismarine-chat and parse it with that.
